### ISSUE TITLE
Missing files in latest release

### ISSUE THREAD

**Issue by wouterfranken** [cp2004/OctoPrint-VirtualPrinterSettings#97]
Hello,

First of all, let me say thanks for this very useful plugin for debugging during plugin development.

Unfortunately, when I tested your latest release it looks like the templates and static assets are missing in your latest release.zip.
This causes malfunction of the plugin: I only see a blank page in the virtualprinter settings.

This seems to be a release issue because when using the source code directly it works without issue.

**Comment by cp2004** [comment]
Yep, the files are missing. I can see the issue - there's two 'manifest' files here and only one of them contains the right information, and neither were changed this time around for the release, but something must have been different for it to break. I'll get that fixed later tonight.

**Comment by cp2004** [comment]
All appears to be good now (with 2022.07.04). Let me know if you have any further issues.
