### ISSUE TITLE
Can't switch back to physical Printer - latest version.

### ISSUE THREAD

**Issue by Thisismydigitalself** [cp2004/OctoPrint-VirtualPrinterSettings#98]
Great plugin. used it today, works like a charm, but when i wanted to switch back to my physical printer, no joy. i was given the option to chose which printer to connect to but OctoPi failed to connect. restarting octoprint did not help, restarting system solved the issue and i could again chose which printer to connect to. more info will be provided upon request.

cheers.

**Comment by cp2004** [comment]
This plugin doesn't provide the 'virtual printer' itself, it is just a settings page. I would recommend reaching our on the [community forums](https://community.octoprint.org) or [discord server](https://discord.octoprint.org) if you need help connecting to your physical printer.
