### ISSUE TITLE
It doesn't work.  Ever.  

### ISSUE THREAD

**Issue by murphykam** [cp2004/OctoPrint-VirtualPrinterSettings#99]
I check the box, fill in some fields and the virtual printer never appears in the list.  I have no printers hooked to it right now, so I just want to have the virtual printer so I can use the timelapse because Octoprint doesn't connect to Bambu.

**Comment by cp2004** [comment]
This plugin doesn't provide the actual virtual printer, just the settings interface for the built in feature in OctoPrint. If you're having trouble with that, I'd recommend trying the [community forums](https://community.octoprint.org) or [discord server](https://discord.octoprint.org) for help.

Using OctoPrint just for timelapse seems a bit overkill to me - I would probably go with standalone timelapse software instead anyway. The virtual printer is designed as a development tool, and as such processes the gcode far faster than a real printer, so it could be quite difficult to time it to the same as a real printer.
